###List all items
GET http://localhost:8000/all
Content-Type: application/json

###Get item by id
GET http://localhost:8000/2
Content-Type: application/json

###Retrieve 2 from item 2
PATCH http://localhost:8000/retrieve/2/2
Content-Type: application/json

###Add 2 from item 2
PATCH http://localhost:8000/add/2/2
Content-Type: application/json

###Create new item
POST http://localhost:8000/
Content-Type: application/json

{
  "name": "berries",
  "quantity": 10
}

###
